project:
  type: website
  output-dir: docs

website:
  title: "H. Emre Etlioglu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cheatsheets.qmd
      - tutorials.qmd

format:
  html:
    theme:
      - default
    css: styles.css
    toc: true
    code-line-numbers: true
