project:
  type: website
  output-dir: docs

website:
  title: "H. Emre Etlioglu"
  navbar:
    background: "#e54e21"
    foreground: "#eeeef0"
    left:
      - href: index.qmd
        text: Home
      - cheatsheets.qmd
      - tutorials.qmd
      - resources.qmd
      - notes.qmd
      - scripts.qmd

format:
  html:
    backgroundcolor: "#f6f1e6"
    fontcolor: "#055756"
    css: styles.css
    toc: true
    code-line-numbers: true
    code-copy: true
